fields:
- name: magento_version
  caption: Magento version
  type: list
  values:
      https://download.jelastic.com/public.php?service=files&t=7536b3f49a99a4d0b9a4ee36ed8e1abe&download: Magento CE 2.4.x
      https://download.jelastic.com/public.php?service=files&t=4946dcdb1a124dda759aac9eed09deb7&download: Magento CE 1.9.4.x
  default: https://download.jelastic.com/public.php?service=files&t=7536b3f49a99a4d0b9a4ee36ed8e1abe&download

- caption: Regions
  type: regionlist
  name: regions
  disableInactive: true
  selectFirstAvailable: true
  multiSelect: false

- caption: Environment
  type: envname
  name: envName
  randomName: true
  showFullDomain: true
  required: true
  dependsOn: regions
